# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6e433a5677ff39c9fc05e910f6592b4955a0323d481fbeb26ce564e49ffab8d05d2ba9d935a47a1499299ad7dff305411d1513873c9c5c5fa147f2d00e43801

test:
  secret_key_base: 177f901dddc7fbb76405867cc606efed5259069c6071b2e27d0dafb76f153ee7fddebcfc8ffe8b2ed4d2250f54f45f487c9b51332235586ee07964dab7ef42c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
